name: "HASS wg-easy UI"
description: "WireGuard UI (wg-easy) for VPN Server"
version: "latest"
slug: "wg_ui"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: ghcr.io/wg-easy/wg-easy
ingress: true
panels:
    name: "WireGuard VPN"
    icon: mdi:vpn
    url: "http://localhost:51821"
