name: "HASS wg-easy UI"
description: "WireGuard UI (wg-easy) for VPN Server"
version: "0.10 (testing)"
slug: "wg_ui"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: ghcr.io/wg-easy/wg-easy
ingress: true
ingress_port: 51821
